# Keep-Alive all GitHub Workflows so they don't stop working after 60 days of
# inactivity. This workflow prevents that through running an action that will
# disable, then enable all active workflows of this repository.
name: keepalive

on:
  schedule:
    # Run every sunday at 1:27 UTC
    - cron: '27 1 * * SUN'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: keepalive
        uses: efrecon/gh-action-keepalive@main
