name: Pack

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - feature/module

jobs:
  pack:
    name: Pack
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Discover the semantic version to use
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.1.0

      - name: Create Storage
        run: mkdir -p pack/mg.sh-${{ steps.semver.outputs.semver }}

      - name: Pack
        run: bin/pack.sh -o pack/mg.sh-${{ steps.semver.outputs.semver }}/mg.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mg.sh
          path: pack/**/*.sh
