name: Pack

on:
  push:
    branches:
      - main

jobs:
  pack:
    name: Pack
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Discover the semantic version to use
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.1.1

      - name: Unit Tests
        run: |
          docker run \
            --rm \
            -v $(pwd):/mg.sh:ro \
            -w /mg.sh \
            -u $(id -u):$(id -g) \
            shellspec/shellspec \
              --format d

      - name: Create Storage
        run: mkdir -p pack/mg-${{ steps.semver.outputs.semver }}.sh

      - name: Pack
        run: bin/pack.sh -o pack/mg-${{ steps.semver.outputs.semver }}.sh/mg.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mg-${{ steps.semver.outputs.semver }}.sh
          path: pack/**/*.sh

      - name: Cleanup
        run: rm -rf pack
