name: Pack

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - feature/module

jobs:
  pack:
    name: Pack
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Discover the semantic version to use
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.1.0

      - name: Create Storage
        run: mkdir -p pack/mg-${{ steps.semver.outputs.semver }}.sh

      - name: Pack
        run: bin/pack.sh -o pack/mg-${{ steps.semver.outputs.semver }}.sh/mg.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mg-${{ steps.semver.outputs.semver }}.sh
          path: pack/**/*.sh

      - name: Cleanup
        run: rm -rf pack

  release:
    name: Relase
    runs-on: ubuntu-latest
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Discover the semantic version to use
      - name: Semantic build-version
        id: semver
        uses: Mitigram/gh-action-versioning@v0.1.0

      - name: Create Directories
        run: |
          mkdir -p mg-${{ steps.semver.outputs.semver }}.sh
          mkdir -p tmp

      - name: Pack
        run: bin/pack.sh -o mg-${{ steps.semver.outputs.semver }}.sh/mg.sh

      - name: Add static files
        run: cp README.md CHANGELOG.md LICENSE mg-${{ steps.semver.outputs.semver }}.sh/

      - name: Create Release Notes
        run: |
          awk "/^## / { p=0 }; p; /^## ${{ steps.semver.outputs.tag }}/ { p=1 }" CHANGELOG.md > relnotes.md

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.tag }}
          body: ${{ steps.semver.outputs.tag }}
          body_path: tmp/relnotes.md
          files: |
            mg-${{ steps.semver.outputs.semver }}.sh/*

      - name: Cleanup
        run: rm -rf mg-${{ steps.semver.outputs.semver }}.sh tmp
