name: Pull Request

on:
  push:
    branches:
      - 'feature/*'

jobs:
  test:
    name: Test
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unit Tests
        run: |
          docker run \
            -it --rm \
            -v $(pwd):/mg.sh \
            -w /mg.sh \
            -u $(id -u):$(id -g) \
            shellspec/shellspec
